modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Bluperman949/clickthroughsigns-mod/issues"
license = "MIT"

[[mods]]
modId = "clickthroughsigns"
version = "${version}"
displayName = "Click Through Signs"
authors = "Bluperman949"
description = '''
'''
logoFile = "icon.png"

[[dependencies.clickthroughsigns]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clickthroughsigns]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "clickthroughsigns.mixins.json"
